#Task to Enable Epel repo
---

- name: Install MariaDB
  yum:
    name: 
     - mariadb-server
     - mariadb

- name: Start the MariaDB service
  action: service name=mariadb state=started

- name: Remove the test database
  mysql_db: name=test state=absent

- name: Copy WordPress config file
  template: src=wp-config.php dest=/var/www/vhosts/demo.com/

- name: Set ownership on vhost
  file:
    path: /var/www/vhosts/demo.com/wp-config.php
    owner: apache
    group: apache

- name: Create a new WordPress database
  mysql_db:
    config_file: "/etc/mysql/my.cnf"
    name: "{{wp_db_name}}"
    state: present
 
- name: Create a new database user and password
  mysql_user:
    config_file: "/etc/mysql/my.cnf"
    name: "{{wp_db_username}}"
    password: "{{wp_db_password}}"
    priv: '{{wp_db_name}}.*:ALL'
    state: present
