---

- name: Add remi-php71
  yum_repository:
    name: remi-php71
    description: Remi's PHP 7.1 RPM repository for Enterprise Linux $releasever - $basearch
    mirrorlist: http://rpms.remirepo.net/enterprise/$releasever/php71/mirror
    enabled: yes
    gpgcheck: 1
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name : enable remi-php71
  shell: yum-config-manager --enable remi-php71

