#Task to Enable Epel repo
---

- name: Install basic tools 
  yum:
    name: 
     - ncdu
     - unzip
     - traceroute
     - vim
     - atop
     - wget
     - vim
     - mlocate
     - net-tools
     - iptables-services
