---
epel_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

remi_repo_url: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
remi_repo_gpg_key_url: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"

base_packages:
  - bc
  - screen
  - vim-enhanced
  - zlib-devel
  - gcc
  - gcc-c++
  - make
  - tcpdump
  - lsof
  - wget
  - telnet
  - pcre-devel
  - screen
  - MySQL-python
  - yum-utils  

base_epel_packages:
  - atop
  - pwgen
  - libmcrypt
  - redis

php_version: '7.3'

php71_packages:
  - php71
  - php71-php-common
  - php71-php-iconv
  - php71-php-mbstring
  - php71-php-curl
  - php71-php-openssl
  - php71-php-tokenizer
  - php71-php-xmlrpc
  - php71-php-soap
  - php71-php-ctype
  - php71-php-gd
  - php71-php-xml
  - php71-php-intl
  - php71-php-json
  - php71-php-pecl-redis
  - php71-php-opcache
  - php71-php-mysqlnd
  - php71-php-pdo
  - php71-php-pecl-imagick

sysctls:
  - { name: vm.swappiness, value: 1 }
  - { name: vm.overcommit_memory, value: 1 }
  - { name: vm.panic_on_oom, value: 1 }
  - { name: kernel.panic, value: 5 }

apache_daemon: httpd
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/httpd
apache_conf_path: /etc/httpd/conf.d

apache_vhosts_version: "2.4"

__apache_packages:
  - httpd
  - httpd-devel  

apache_create_vhosts: "true"
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"
apache_remove_default_vhost: "false"

apache_ports_configuration_items:
  - regexp: "^Listen "
    line: "Listen 80"

wp_db_name: 'democom'
wp_db_username: 'decom'
wp_db_password: "ZJa1x8fl"
wp_db_host: 'localhost'
wp_table_prefix: 'wp_'
wp_debug_mode: 'FALSE'

WP_DOMAIN: demo.com
WP_ADMIN_USERNAME: demo
WP_ADMIN_EMAIL: me@demo.com
WP_ADMIN_PASSWORD: JkiloE9upp)nElURQh

